# Everyone uses the ubuntu user on Ubuntu AMIs
ansible_user: ubuntu

# Your local private key (do NOT copy to bastion)
ansible_ssh_private_key_file: ~/.ssh/kubeadm-aws-key

# Enable agent forwarding
ansible_ssh_common_args: "-o ForwardAgent=yes"
