---
- name: Initialize Kubernetes Master Node
  hosts: master
  become: yes

  tasks:
    - name: Check if kubeadm is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Initialize Kubernetes control plane
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: not kubeconfig.stat.exists

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      when: not kubeconfig.stat.exists

    - name: Copy kubeconfig to ubuntu user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
      when: not kubeconfig.stat.exists

    - name: Deploy Calico CNI
      become_user: ubuntu
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: not kubeconfig.stat.exists
